### ISSUE TITLE
Add filters to query and output

### ISSUE THREAD

**Issue by dougaxe1** [WDGDC/Jarvis#16]
Add custom filters in `get_search_results` to alter the query and results before returning.

Post results should include standard WP filters for `the_title` and similar.

**Comment by dougaxe1** [comment]
Proposed filters:

`private function search_post_id($id = null)`:
* Remove `apply_filters('the_title', $post->post_title)` as this can be handled in normalize (see below)

`private function normalize($result)`:
* Add `$result->title = apply_filters('the_title', $result->title, $result->id);` - alter title
* Add `$result = apply_filters('jarvis_normalize', $result);` - alter any aspect of result

`public function get_search_results()`:
* `$exclude_post_statuses = apply_filters('jarvis_exclude_post_statuses', $exclude_post_statuses);` - default excludes: `revision`, `auto-draft` and `trash` (see #17)
* `$include_post_types = apply_filters('jarvis_include_post_types', $include_post_types);` - default includes `get_post_types(array('show_ui' => true))`
* `$this->results = apply_filters('jarvis_results', $this->results, $_REQUEST['q']);` - filter all results before returning

**Comment by kshaner** [comment]
Fixed in #23, filters and actions are documented inline and will be documented on the wiki
