### ISSUE TITLE
Improve handling of trashed items

### ISSUE THREAD

**Issue by dougaxe1** [WDGDC/Jarvis#17]
Original report by @vajaah.

Trashed items appear alongside published and draft items in keyword search, so clicking on them shows an error message:

![image](https://user-images.githubusercontent.com/10548206/46613164-835a0500-cae0-11e8-8284-8f61ce9741d8.png)

Also, add a filter to exclude items in the trash from appearing at all (filter by status)

**Comment by dougaxe1** [comment]
Per #16, we can exclude trash items by default, not sure if that solves it.

**Comment by kshaner** [comment]
Fixed in #23.  Now trashed items are excluded by default.
