### ISSUE TITLE
Warning on all admin pages

### ISSUE THREAD

**Issue by schwartzman** [WDGDC/Jarvis#25]
> Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Jarvis\Plugin' not found in /wp-includes/class-wp-hook.php on line 286

**Comment by dougaxe1** [comment]
Related to: 
https://wordpress.org/support/topic/warning-after-updating-to-v-1-0-0/
https://wordpress.org/support/topic/warning-after-updating-to-v-1-0-1/

Please update status on wp.org with resolution.

**Comment by Anguel** [comment]
Could the source of this bug be identified or may this be related to specific hosting providers?

**Comment by kshaner** [comment]
@schwartzman and @Anguel, this should be fixed in 1.0.4, it was a bug in the autoloader that was converting too much of the path.  So a webroot label `public_html` would fail where `www` worked just fine.

**Comment by schwartzman** [comment]
@kshaner Thank you!
