### ISSUE TITLE
Jarvis Commands

### ISSUE THREAD

**Issue by vajaah** [WDGDC/Jarvis#5]
"Add a way to log out via Jarvis. So if I type "/ log out" and then hit enter, it logs me out of Wordpress. Alfred does something similar on the Mac."

-- via Matthew

**Comment by josephfusco** [comment]
:+1: for this even if this is a pretty old issue. :smile:

**Comment by neojp** [comment]
A few ideas:

- [ ] Reset permalinks structure

**Comment by kshaner** [comment]
Jarvis 1.0.0 now has basic support for commands including logout and reset permalinks.  More commands will come in future releases.  Fixed in #23.
